trigger:
  branches:
    include:
      - master

pr: none

pool:
  name: eSim-AgentPool  # or your self-hosted agent name

variables:
  buildConfiguration: 'Release'
jobs:
 - job: Build_Selfcare
   condition: contains(variables['Build.SourceVersionMessage'],'[selfcare-proj]')
   steps:
   - task: UseDotNet@2
     inputs:
      packageType: 'sdk'
      version: '9.0.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet

   - script: dotnet restore eSim.Selfcare/eSim.Selfcare.csproj
     displayName: 'Restore eSim Selfcare project'

   - script: dotnet build eSim.Selfcare/eSim.Selfcare.csproj --configuration $(buildConfiguration)
     displayName: 'Build eSim Selfcare project'

   - script: dotnet publish eSim.Selfcare/eSim.Selfcare.csproj --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/selfcare
     displayName: 'Publish eSim Selfcare project'

   - task: PublishBuildArtifacts@1
     inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/selfcare'
      ArtifactName: 'selfcare-web-artifact'
      publishLocation: 'Container'
