// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eSim.EF.Context;

#nullable disable

namespace eSim.EF.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250602123134_AddedUserIdInClients")]
    partial class AddedUserIdInClients
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasDiscriminator().HasValue("IdentityRole");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator().HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("eSim.EF.Entities.AspNetUsersType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AspNetUsersType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Type = "Developer"
                        },
                        new
                        {
                            Id = 2,
                            Type = "Superadmin"
                        },
                        new
                        {
                            Id = 3,
                            Type = "Subadmin"
                        },
                        new
                        {
                            Id = 4,
                            Type = "Client"
                        },
                        new
                        {
                            Id = 5,
                            Type = "Subclient"
                        });
                });

            modelBuilder.Entity("eSim.EF.Entities.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Kid")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PrimaryEmail")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Secret")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clients", "master");
                });

            modelBuilder.Entity("eSim.EF.Entities.ClientSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("FixedCommission")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Settings", "client");
                });

            modelBuilder.Entity("eSim.EF.Entities.Countries", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Iso2")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Iso3")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("Id");

                    b.ToTable("Countries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryName = "Afghanistan",
                            Iso2 = "AF",
                            Iso3 = "AFG"
                        },
                        new
                        {
                            Id = 2,
                            CountryName = "Aland Islands",
                            Iso2 = "AX",
                            Iso3 = "ALA"
                        },
                        new
                        {
                            Id = 3,
                            CountryName = "Albania",
                            Iso2 = "AL",
                            Iso3 = "ALB"
                        },
                        new
                        {
                            Id = 4,
                            CountryName = "Algeria",
                            Iso2 = "DZ",
                            Iso3 = "DZA"
                        },
                        new
                        {
                            Id = 5,
                            CountryName = "American Samoa",
                            Iso2 = "AS",
                            Iso3 = "ASM"
                        },
                        new
                        {
                            Id = 6,
                            CountryName = "Andorra",
                            Iso2 = "AD",
                            Iso3 = "AND"
                        },
                        new
                        {
                            Id = 7,
                            CountryName = "Angola",
                            Iso2 = "AO",
                            Iso3 = "AGO"
                        },
                        new
                        {
                            Id = 8,
                            CountryName = "Anguilla",
                            Iso2 = "AI",
                            Iso3 = "AIA"
                        },
                        new
                        {
                            Id = 9,
                            CountryName = "Antarctica",
                            Iso2 = "AQ",
                            Iso3 = "ATA"
                        },
                        new
                        {
                            Id = 10,
                            CountryName = "Antigua And Barbuda",
                            Iso2 = "AG",
                            Iso3 = "ATG"
                        },
                        new
                        {
                            Id = 11,
                            CountryName = "Argentina",
                            Iso2 = "AR",
                            Iso3 = "ARG"
                        },
                        new
                        {
                            Id = 12,
                            CountryName = "Armenia",
                            Iso2 = "AM",
                            Iso3 = "ARM"
                        },
                        new
                        {
                            Id = 13,
                            CountryName = "Aruba",
                            Iso2 = "AW",
                            Iso3 = "ABW"
                        },
                        new
                        {
                            Id = 14,
                            CountryName = "Australia",
                            Iso2 = "AU",
                            Iso3 = "AUS"
                        },
                        new
                        {
                            Id = 15,
                            CountryName = "Austria",
                            Iso2 = "AT",
                            Iso3 = "AUT"
                        },
                        new
                        {
                            Id = 16,
                            CountryName = "Azerbaijan",
                            Iso2 = "AZ",
                            Iso3 = "AZE"
                        },
                        new
                        {
                            Id = 17,
                            CountryName = "Bahamas The",
                            Iso2 = "BS",
                            Iso3 = "BHS"
                        },
                        new
                        {
                            Id = 18,
                            CountryName = "Bahrain",
                            Iso2 = "BH",
                            Iso3 = "BHR"
                        },
                        new
                        {
                            Id = 19,
                            CountryName = "Bangladesh",
                            Iso2 = "BD",
                            Iso3 = "BGD"
                        },
                        new
                        {
                            Id = 20,
                            CountryName = "Barbados",
                            Iso2 = "BB",
                            Iso3 = "BRB"
                        },
                        new
                        {
                            Id = 21,
                            CountryName = "Belarus",
                            Iso2 = "BY",
                            Iso3 = "BLR"
                        },
                        new
                        {
                            Id = 22,
                            CountryName = "Belgium",
                            Iso2 = "BE",
                            Iso3 = "BEL"
                        },
                        new
                        {
                            Id = 23,
                            CountryName = "Belize",
                            Iso2 = "BZ",
                            Iso3 = "BLZ"
                        },
                        new
                        {
                            Id = 24,
                            CountryName = "Benin",
                            Iso2 = "BJ",
                            Iso3 = "BEN"
                        },
                        new
                        {
                            Id = 25,
                            CountryName = "Bermuda",
                            Iso2 = "BM",
                            Iso3 = "BMU"
                        },
                        new
                        {
                            Id = 26,
                            CountryName = "Bhutan",
                            Iso2 = "BT",
                            Iso3 = "BTN"
                        },
                        new
                        {
                            Id = 27,
                            CountryName = "Bolivia",
                            Iso2 = "BO",
                            Iso3 = "BOL"
                        },
                        new
                        {
                            Id = 28,
                            CountryName = "Bosnia and Herzegovina",
                            Iso2 = "BA",
                            Iso3 = "BIH"
                        },
                        new
                        {
                            Id = 29,
                            CountryName = "Botswana",
                            Iso2 = "BW",
                            Iso3 = "BWA"
                        },
                        new
                        {
                            Id = 30,
                            CountryName = "Bouvet Island",
                            Iso2 = "BV",
                            Iso3 = "BVT"
                        },
                        new
                        {
                            Id = 31,
                            CountryName = "Brazil",
                            Iso2 = "BR",
                            Iso3 = "BRA"
                        },
                        new
                        {
                            Id = 32,
                            CountryName = "British Indian Ocean Territory",
                            Iso2 = "IO",
                            Iso3 = "IOT"
                        },
                        new
                        {
                            Id = 33,
                            CountryName = "Brunei",
                            Iso2 = "BN",
                            Iso3 = "BRN"
                        },
                        new
                        {
                            Id = 34,
                            CountryName = "Bulgaria",
                            Iso2 = "BG",
                            Iso3 = "BGR"
                        },
                        new
                        {
                            Id = 35,
                            CountryName = "Burkina Faso",
                            Iso2 = "BF",
                            Iso3 = "BFA"
                        },
                        new
                        {
                            Id = 36,
                            CountryName = "Burundi",
                            Iso2 = "BI",
                            Iso3 = "BDI"
                        },
                        new
                        {
                            Id = 37,
                            CountryName = "Cambodia",
                            Iso2 = "KH",
                            Iso3 = "KHM"
                        },
                        new
                        {
                            Id = 38,
                            CountryName = "Cameroon",
                            Iso2 = "CM",
                            Iso3 = "CMR"
                        },
                        new
                        {
                            Id = 39,
                            CountryName = "Canada",
                            Iso2 = "CA",
                            Iso3 = "CAN"
                        },
                        new
                        {
                            Id = 40,
                            CountryName = "Cape Verde",
                            Iso2 = "CV",
                            Iso3 = "CPV"
                        },
                        new
                        {
                            Id = 41,
                            CountryName = "Cayman Islands",
                            Iso2 = "KY",
                            Iso3 = "CYM"
                        },
                        new
                        {
                            Id = 42,
                            CountryName = "Central African Republic",
                            Iso2 = "CF",
                            Iso3 = "CAF"
                        },
                        new
                        {
                            Id = 43,
                            CountryName = "Chad",
                            Iso2 = "TD",
                            Iso3 = "TCD"
                        },
                        new
                        {
                            Id = 44,
                            CountryName = "Chile",
                            Iso2 = "CL",
                            Iso3 = "CHL"
                        },
                        new
                        {
                            Id = 45,
                            CountryName = "China",
                            Iso2 = "CN",
                            Iso3 = "CHN"
                        },
                        new
                        {
                            Id = 46,
                            CountryName = "Christmas Island",
                            Iso2 = "CX",
                            Iso3 = "CXR"
                        },
                        new
                        {
                            Id = 47,
                            CountryName = "Cocos (Keeling) Islands",
                            Iso2 = "CC",
                            Iso3 = "CCK"
                        },
                        new
                        {
                            Id = 48,
                            CountryName = "Colombia",
                            Iso2 = "CO",
                            Iso3 = "COL"
                        },
                        new
                        {
                            Id = 49,
                            CountryName = "Comoros",
                            Iso2 = "KM",
                            Iso3 = "COM"
                        },
                        new
                        {
                            Id = 50,
                            CountryName = "Congo, The Republic of",
                            Iso2 = "CG",
                            Iso3 = "COG"
                        },
                        new
                        {
                            Id = 51,
                            CountryName = "Congo The Democratic Republic Of The",
                            Iso2 = "CD",
                            Iso3 = "COD"
                        },
                        new
                        {
                            Id = 52,
                            CountryName = "Cook Islands",
                            Iso2 = "CK",
                            Iso3 = "COK"
                        },
                        new
                        {
                            Id = 53,
                            CountryName = "Costa Rica",
                            Iso2 = "CR",
                            Iso3 = "CRI"
                        },
                        new
                        {
                            Id = 54,
                            CountryName = "Cote D'Ivoire (Ivory Coast)",
                            Iso2 = "CI",
                            Iso3 = "CIV"
                        },
                        new
                        {
                            Id = 55,
                            CountryName = "Croatia (Hrvatska)",
                            Iso2 = "HR",
                            Iso3 = "HRV"
                        },
                        new
                        {
                            Id = 56,
                            CountryName = "Cuba",
                            Iso2 = "CU",
                            Iso3 = "CUB"
                        },
                        new
                        {
                            Id = 57,
                            CountryName = "Cyprus, Republic of",
                            Iso2 = "CY",
                            Iso3 = "CYP"
                        },
                        new
                        {
                            Id = 58,
                            CountryName = "Czech Republic",
                            Iso2 = "CZ",
                            Iso3 = "CZE"
                        },
                        new
                        {
                            Id = 59,
                            CountryName = "Denmark",
                            Iso2 = "DK",
                            Iso3 = "DNK"
                        },
                        new
                        {
                            Id = 60,
                            CountryName = "Djibouti",
                            Iso2 = "DJ",
                            Iso3 = "DJI"
                        },
                        new
                        {
                            Id = 61,
                            CountryName = "Dominica",
                            Iso2 = "DM",
                            Iso3 = "DMA"
                        },
                        new
                        {
                            Id = 62,
                            CountryName = "Dominican Republic",
                            Iso2 = "DO",
                            Iso3 = "DOM"
                        },
                        new
                        {
                            Id = 63,
                            CountryName = "East Timor",
                            Iso2 = "TL",
                            Iso3 = "TLS"
                        },
                        new
                        {
                            Id = 64,
                            CountryName = "Ecuador",
                            Iso2 = "EC",
                            Iso3 = "ECU"
                        },
                        new
                        {
                            Id = 65,
                            CountryName = "Egypt",
                            Iso2 = "EG",
                            Iso3 = "EGY"
                        },
                        new
                        {
                            Id = 66,
                            CountryName = "El Salvador",
                            Iso2 = "SV",
                            Iso3 = "SLV"
                        },
                        new
                        {
                            Id = 67,
                            CountryName = "Equatorial Guinea",
                            Iso2 = "GQ",
                            Iso3 = "GNQ"
                        },
                        new
                        {
                            Id = 68,
                            CountryName = "Eritrea",
                            Iso2 = "ER",
                            Iso3 = "ERI"
                        },
                        new
                        {
                            Id = 69,
                            CountryName = "Estonia",
                            Iso2 = "EE",
                            Iso3 = "EST"
                        },
                        new
                        {
                            Id = 70,
                            CountryName = "Ethiopia",
                            Iso2 = "ET",
                            Iso3 = "ETH"
                        },
                        new
                        {
                            Id = 71,
                            CountryName = "Falkland Islands",
                            Iso2 = "FK",
                            Iso3 = "FLK"
                        },
                        new
                        {
                            Id = 72,
                            CountryName = "Faroe Islands",
                            Iso2 = "FO",
                            Iso3 = "FRO"
                        },
                        new
                        {
                            Id = 73,
                            CountryName = "Fiji Islands",
                            Iso2 = "FJ",
                            Iso3 = "FJI"
                        },
                        new
                        {
                            Id = 74,
                            CountryName = "Finland",
                            Iso2 = "FI",
                            Iso3 = "FIN"
                        },
                        new
                        {
                            Id = 75,
                            CountryName = "France",
                            Iso2 = "FR",
                            Iso3 = "FRA"
                        },
                        new
                        {
                            Id = 76,
                            CountryName = "French Guiana",
                            Iso2 = "GF",
                            Iso3 = "GUF"
                        },
                        new
                        {
                            Id = 77,
                            CountryName = "French Polynesia",
                            Iso2 = "PF",
                            Iso3 = "PYF"
                        },
                        new
                        {
                            Id = 78,
                            CountryName = "French Southern Territories",
                            Iso2 = "TF",
                            Iso3 = "ATF"
                        },
                        new
                        {
                            Id = 79,
                            CountryName = "Gabon",
                            Iso2 = "GA",
                            Iso3 = "GAB"
                        },
                        new
                        {
                            Id = 80,
                            CountryName = "Gambia The",
                            Iso2 = "GM",
                            Iso3 = "GMB"
                        },
                        new
                        {
                            Id = 81,
                            CountryName = "Georgia",
                            Iso2 = "GE",
                            Iso3 = "GEO"
                        },
                        new
                        {
                            Id = 82,
                            CountryName = "Germany",
                            Iso2 = "DE",
                            Iso3 = "DEU"
                        },
                        new
                        {
                            Id = 83,
                            CountryName = "Ghana",
                            Iso2 = "GH",
                            Iso3 = "GHA"
                        },
                        new
                        {
                            Id = 84,
                            CountryName = "Gibraltar",
                            Iso2 = "GI",
                            Iso3 = "GIB"
                        },
                        new
                        {
                            Id = 85,
                            CountryName = "Greece",
                            Iso2 = "GR",
                            Iso3 = "GRC"
                        },
                        new
                        {
                            Id = 86,
                            CountryName = "Greenland",
                            Iso2 = "GL",
                            Iso3 = "GRL"
                        },
                        new
                        {
                            Id = 87,
                            CountryName = "Grenada",
                            Iso2 = "GD",
                            Iso3 = "GRD"
                        },
                        new
                        {
                            Id = 88,
                            CountryName = "Guadeloupe",
                            Iso2 = "GP",
                            Iso3 = "GLP"
                        },
                        new
                        {
                            Id = 89,
                            CountryName = "Guam",
                            Iso2 = "GU",
                            Iso3 = "GUM"
                        },
                        new
                        {
                            Id = 90,
                            CountryName = "Guatemala",
                            Iso2 = "GT",
                            Iso3 = "GTM"
                        },
                        new
                        {
                            Id = 91,
                            CountryName = "Guernsey and Alderney",
                            Iso2 = "GG",
                            Iso3 = "GGY"
                        },
                        new
                        {
                            Id = 92,
                            CountryName = "Guinea",
                            Iso2 = "GN",
                            Iso3 = "GIN"
                        },
                        new
                        {
                            Id = 93,
                            CountryName = "Guinea-Bissau",
                            Iso2 = "GW",
                            Iso3 = "GNB"
                        },
                        new
                        {
                            Id = 94,
                            CountryName = "Guyana",
                            Iso2 = "GY",
                            Iso3 = "GUY"
                        },
                        new
                        {
                            Id = 95,
                            CountryName = "Haiti",
                            Iso2 = "HT",
                            Iso3 = "HTI"
                        },
                        new
                        {
                            Id = 96,
                            CountryName = "Heard Island and McDonald Islands",
                            Iso2 = "HM",
                            Iso3 = "HMD"
                        },
                        new
                        {
                            Id = 97,
                            CountryName = "Honduras",
                            Iso2 = "HN",
                            Iso3 = "HND"
                        },
                        new
                        {
                            Id = 98,
                            CountryName = "Hong Kong S.A.R.",
                            Iso2 = "HK",
                            Iso3 = "HKG"
                        },
                        new
                        {
                            Id = 99,
                            CountryName = "Hungary",
                            Iso2 = "HU",
                            Iso3 = "HUN"
                        },
                        new
                        {
                            Id = 100,
                            CountryName = "Iceland",
                            Iso2 = "IS",
                            Iso3 = "ISL"
                        },
                        new
                        {
                            Id = 101,
                            CountryName = "India",
                            Iso2 = "IN",
                            Iso3 = "IND"
                        },
                        new
                        {
                            Id = 102,
                            CountryName = "Indonesia",
                            Iso2 = "ID",
                            Iso3 = "IDN"
                        },
                        new
                        {
                            Id = 103,
                            CountryName = "Iran",
                            Iso2 = "IR",
                            Iso3 = "IRN"
                        },
                        new
                        {
                            Id = 104,
                            CountryName = "Iraq",
                            Iso2 = "IQ",
                            Iso3 = "IRQ"
                        },
                        new
                        {
                            Id = 105,
                            CountryName = "Ireland",
                            Iso2 = "IE",
                            Iso3 = "IRL"
                        },
                        new
                        {
                            Id = 106,
                            CountryName = "Israel",
                            Iso2 = "IL",
                            Iso3 = "ISR"
                        },
                        new
                        {
                            Id = 107,
                            CountryName = "Italy",
                            Iso2 = "IT",
                            Iso3 = "ITA"
                        },
                        new
                        {
                            Id = 108,
                            CountryName = "Jamaica",
                            Iso2 = "JM",
                            Iso3 = "JAM"
                        },
                        new
                        {
                            Id = 109,
                            CountryName = "Japan",
                            Iso2 = "JP",
                            Iso3 = "JPN"
                        },
                        new
                        {
                            Id = 110,
                            CountryName = "Jersey",
                            Iso2 = "JE",
                            Iso3 = "JEY"
                        },
                        new
                        {
                            Id = 111,
                            CountryName = "Jordan",
                            Iso2 = "JO",
                            Iso3 = "JOR"
                        },
                        new
                        {
                            Id = 112,
                            CountryName = "Kazakhstan",
                            Iso2 = "KZ",
                            Iso3 = "KAZ"
                        },
                        new
                        {
                            Id = 113,
                            CountryName = "Kenya",
                            Iso2 = "KE",
                            Iso3 = "KEN"
                        },
                        new
                        {
                            Id = 114,
                            CountryName = "Kiribati",
                            Iso2 = "KI",
                            Iso3 = "KIR"
                        },
                        new
                        {
                            Id = 115,
                            CountryName = "South Korea (Republic of)",
                            Iso2 = "KP",
                            Iso3 = "PRK"
                        },
                        new
                        {
                            Id = 116,
                            CountryName = "North Korea (Democratic People's Republic of)",
                            Iso2 = "KR",
                            Iso3 = "KOR"
                        },
                        new
                        {
                            Id = 117,
                            CountryName = "Kuwait",
                            Iso2 = "KW",
                            Iso3 = "KWT"
                        },
                        new
                        {
                            Id = 118,
                            CountryName = "Kyrgyzstan",
                            Iso2 = "KG",
                            Iso3 = "KGZ"
                        },
                        new
                        {
                            Id = 119,
                            CountryName = "Laos",
                            Iso2 = "LA",
                            Iso3 = "LAO"
                        },
                        new
                        {
                            Id = 120,
                            CountryName = "Latvia",
                            Iso2 = "LV",
                            Iso3 = "LVA"
                        },
                        new
                        {
                            Id = 121,
                            CountryName = "Lebanon",
                            Iso2 = "LB",
                            Iso3 = "LBN"
                        },
                        new
                        {
                            Id = 122,
                            CountryName = "Lesotho",
                            Iso2 = "LS",
                            Iso3 = "LSO"
                        },
                        new
                        {
                            Id = 123,
                            CountryName = "Liberia",
                            Iso2 = "LR",
                            Iso3 = "LBR"
                        },
                        new
                        {
                            Id = 124,
                            CountryName = "Libya",
                            Iso2 = "LY",
                            Iso3 = "LBY"
                        },
                        new
                        {
                            Id = 125,
                            CountryName = "Liechtenstein",
                            Iso2 = "LI",
                            Iso3 = "LIE"
                        },
                        new
                        {
                            Id = 126,
                            CountryName = "Lithuania",
                            Iso2 = "LT",
                            Iso3 = "LTU"
                        },
                        new
                        {
                            Id = 127,
                            CountryName = "Luxembourg",
                            Iso2 = "LU",
                            Iso3 = "LUX"
                        },
                        new
                        {
                            Id = 128,
                            CountryName = "Macau S.A.R.",
                            Iso2 = "MO",
                            Iso3 = "MAC"
                        },
                        new
                        {
                            Id = 129,
                            CountryName = "North Macedonia",
                            Iso2 = "MK",
                            Iso3 = "MKD"
                        },
                        new
                        {
                            Id = 130,
                            CountryName = "Madagascar",
                            Iso2 = "MG",
                            Iso3 = "MDG"
                        },
                        new
                        {
                            Id = 131,
                            CountryName = "Malawi",
                            Iso2 = "MW",
                            Iso3 = "MWI"
                        },
                        new
                        {
                            Id = 132,
                            CountryName = "Malaysia",
                            Iso2 = "MY",
                            Iso3 = "MYS"
                        },
                        new
                        {
                            Id = 133,
                            CountryName = "Maldives",
                            Iso2 = "MV",
                            Iso3 = "MDV"
                        },
                        new
                        {
                            Id = 134,
                            CountryName = "Mali",
                            Iso2 = "ML",
                            Iso3 = "MLI"
                        },
                        new
                        {
                            Id = 135,
                            CountryName = "Malta",
                            Iso2 = "MT",
                            Iso3 = "MLT"
                        },
                        new
                        {
                            Id = 136,
                            CountryName = "Man (Isle of)",
                            Iso2 = "IM",
                            Iso3 = "IMN"
                        },
                        new
                        {
                            Id = 137,
                            CountryName = "Marshall Islands",
                            Iso2 = "MH",
                            Iso3 = "MHL"
                        },
                        new
                        {
                            Id = 138,
                            CountryName = "Martinique",
                            Iso2 = "MQ",
                            Iso3 = "MTQ"
                        },
                        new
                        {
                            Id = 139,
                            CountryName = "Mauritania",
                            Iso2 = "MR",
                            Iso3 = "MRT"
                        },
                        new
                        {
                            Id = 140,
                            CountryName = "Mauritius",
                            Iso2 = "MU",
                            Iso3 = "MUS"
                        },
                        new
                        {
                            Id = 141,
                            CountryName = "Mayotte",
                            Iso2 = "YT",
                            Iso3 = "MYT"
                        },
                        new
                        {
                            Id = 142,
                            CountryName = "Mexico",
                            Iso2 = "MX",
                            Iso3 = "MEX"
                        },
                        new
                        {
                            Id = 143,
                            CountryName = "Micronesia",
                            Iso2 = "FM",
                            Iso3 = "FSM"
                        },
                        new
                        {
                            Id = 144,
                            CountryName = "Moldova",
                            Iso2 = "MD",
                            Iso3 = "MDA"
                        },
                        new
                        {
                            Id = 145,
                            CountryName = "Monaco",
                            Iso2 = "MC",
                            Iso3 = "MCO"
                        },
                        new
                        {
                            Id = 146,
                            CountryName = "Mongolia",
                            Iso2 = "MN",
                            Iso3 = "MNG"
                        },
                        new
                        {
                            Id = 147,
                            CountryName = "Montenegro",
                            Iso2 = "ME",
                            Iso3 = "MNE"
                        },
                        new
                        {
                            Id = 148,
                            CountryName = "Montserrat",
                            Iso2 = "MS",
                            Iso3 = "MSR"
                        },
                        new
                        {
                            Id = 149,
                            CountryName = "Morocco",
                            Iso2 = "MA",
                            Iso3 = "MAR"
                        },
                        new
                        {
                            Id = 150,
                            CountryName = "Mozambique",
                            Iso2 = "MZ",
                            Iso3 = "MOZ"
                        },
                        new
                        {
                            Id = 151,
                            CountryName = "Myanmar",
                            Iso2 = "MM",
                            Iso3 = "MMR"
                        },
                        new
                        {
                            Id = 152,
                            CountryName = "Namibia",
                            Iso2 = "NA",
                            Iso3 = "NAM"
                        },
                        new
                        {
                            Id = 153,
                            CountryName = "Nauru",
                            Iso2 = "NR",
                            Iso3 = "NRU"
                        },
                        new
                        {
                            Id = 154,
                            CountryName = "Nepal",
                            Iso2 = "NP",
                            Iso3 = "NPL"
                        },
                        new
                        {
                            Id = 155,
                            CountryName = "Bonaire, Sint Eustatius and Saba",
                            Iso2 = "BQ",
                            Iso3 = "BES"
                        },
                        new
                        {
                            Id = 156,
                            CountryName = "Netherlands The",
                            Iso2 = "NL",
                            Iso3 = "NLD"
                        },
                        new
                        {
                            Id = 157,
                            CountryName = "New Caledonia",
                            Iso2 = "NC",
                            Iso3 = "NCL"
                        },
                        new
                        {
                            Id = 158,
                            CountryName = "New Zealand",
                            Iso2 = "NZ",
                            Iso3 = "NZL"
                        },
                        new
                        {
                            Id = 159,
                            CountryName = "Nicaragua",
                            Iso2 = "NI",
                            Iso3 = "NIC"
                        },
                        new
                        {
                            Id = 160,
                            CountryName = "Niger",
                            Iso2 = "NE",
                            Iso3 = "NER"
                        },
                        new
                        {
                            Id = 161,
                            CountryName = "Nigeria",
                            Iso2 = "NG",
                            Iso3 = "NGA"
                        },
                        new
                        {
                            Id = 162,
                            CountryName = "Niue",
                            Iso2 = "NU",
                            Iso3 = "NIU"
                        },
                        new
                        {
                            Id = 163,
                            CountryName = "Norfolk Island",
                            Iso2 = "NF",
                            Iso3 = "NFK"
                        },
                        new
                        {
                            Id = 164,
                            CountryName = "Northern Mariana Islands",
                            Iso2 = "MP",
                            Iso3 = "MNP"
                        },
                        new
                        {
                            Id = 165,
                            CountryName = "Norway",
                            Iso2 = "NO",
                            Iso3 = "NOR"
                        },
                        new
                        {
                            Id = 166,
                            CountryName = "Oman",
                            Iso2 = "OM",
                            Iso3 = "OMN"
                        },
                        new
                        {
                            Id = 167,
                            CountryName = "Pakistan",
                            Iso2 = "PK",
                            Iso3 = "PAK"
                        },
                        new
                        {
                            Id = 168,
                            CountryName = "Palau",
                            Iso2 = "PW",
                            Iso3 = "PLW"
                        },
                        new
                        {
                            Id = 169,
                            CountryName = "Palestine",
                            Iso2 = "PS",
                            Iso3 = "PSE"
                        },
                        new
                        {
                            Id = 170,
                            CountryName = "Panama",
                            Iso2 = "PA",
                            Iso3 = "PAN"
                        },
                        new
                        {
                            Id = 171,
                            CountryName = "Papua New Guinea",
                            Iso2 = "PG",
                            Iso3 = "PNG"
                        },
                        new
                        {
                            Id = 172,
                            CountryName = "Paraguay",
                            Iso2 = "PY",
                            Iso3 = "PRY"
                        },
                        new
                        {
                            Id = 173,
                            CountryName = "Peru",
                            Iso2 = "PE",
                            Iso3 = "PER"
                        },
                        new
                        {
                            Id = 174,
                            CountryName = "Philippines",
                            Iso2 = "PH",
                            Iso3 = "PHL"
                        },
                        new
                        {
                            Id = 175,
                            CountryName = "Pitcairn Island",
                            Iso2 = "PN",
                            Iso3 = "PCN"
                        },
                        new
                        {
                            Id = 176,
                            CountryName = "Poland",
                            Iso2 = "PL",
                            Iso3 = "POL"
                        },
                        new
                        {
                            Id = 177,
                            CountryName = "Portugal",
                            Iso2 = "PT",
                            Iso3 = "PRT"
                        },
                        new
                        {
                            Id = 178,
                            CountryName = "Puerto Rico",
                            Iso2 = "PR",
                            Iso3 = "PRI"
                        },
                        new
                        {
                            Id = 179,
                            CountryName = "Qatar",
                            Iso2 = "QA",
                            Iso3 = "QAT"
                        },
                        new
                        {
                            Id = 180,
                            CountryName = "Reunion",
                            Iso2 = "RE",
                            Iso3 = "REU"
                        },
                        new
                        {
                            Id = 181,
                            CountryName = "Romania",
                            Iso2 = "RO",
                            Iso3 = "ROU"
                        },
                        new
                        {
                            Id = 182,
                            CountryName = "Russia",
                            Iso2 = "RU",
                            Iso3 = "RUS"
                        },
                        new
                        {
                            Id = 183,
                            CountryName = "Rwanda",
                            Iso2 = "RW",
                            Iso3 = "RWA"
                        },
                        new
                        {
                            Id = 184,
                            CountryName = "Saint Helena",
                            Iso2 = "SH",
                            Iso3 = "SHN"
                        },
                        new
                        {
                            Id = 185,
                            CountryName = "Saint Kitts And Nevis",
                            Iso2 = "KN",
                            Iso3 = "KNA"
                        },
                        new
                        {
                            Id = 186,
                            CountryName = "Saint Lucia",
                            Iso2 = "LC",
                            Iso3 = "LCA"
                        },
                        new
                        {
                            Id = 187,
                            CountryName = "Saint Pierre and Miquelon",
                            Iso2 = "PM",
                            Iso3 = "SPM"
                        },
                        new
                        {
                            Id = 188,
                            CountryName = "Saint Vincent And The Grenadines",
                            Iso2 = "VC",
                            Iso3 = "VCT"
                        },
                        new
                        {
                            Id = 189,
                            CountryName = "Saint-Barthelemy",
                            Iso2 = "BL",
                            Iso3 = "BLM"
                        },
                        new
                        {
                            Id = 190,
                            CountryName = "Saint-Martin (French part)",
                            Iso2 = "MF",
                            Iso3 = "MAF"
                        },
                        new
                        {
                            Id = 191,
                            CountryName = "Samoa",
                            Iso2 = "WS",
                            Iso3 = "WSM"
                        },
                        new
                        {
                            Id = 192,
                            CountryName = "San Marino",
                            Iso2 = "SM",
                            Iso3 = "SMR"
                        },
                        new
                        {
                            Id = 193,
                            CountryName = "Sao Tome and Principe",
                            Iso2 = "ST",
                            Iso3 = "STP"
                        },
                        new
                        {
                            Id = 194,
                            CountryName = "Saudi Arabia",
                            Iso2 = "SA",
                            Iso3 = "SAU"
                        },
                        new
                        {
                            Id = 195,
                            CountryName = "Senegal",
                            Iso2 = "SN",
                            Iso3 = "SEN"
                        },
                        new
                        {
                            Id = 196,
                            CountryName = "Serbia",
                            Iso2 = "RS",
                            Iso3 = "SRB"
                        },
                        new
                        {
                            Id = 197,
                            CountryName = "Seychelles",
                            Iso2 = "SC",
                            Iso3 = "SYC"
                        },
                        new
                        {
                            Id = 198,
                            CountryName = "Sierra Leone",
                            Iso2 = "SL",
                            Iso3 = "SLE"
                        },
                        new
                        {
                            Id = 199,
                            CountryName = "Singapore",
                            Iso2 = "SG",
                            Iso3 = "SGP"
                        },
                        new
                        {
                            Id = 200,
                            CountryName = "Slovakia",
                            Iso2 = "SK",
                            Iso3 = "SVK"
                        },
                        new
                        {
                            Id = 201,
                            CountryName = "Slovenia",
                            Iso2 = "SI",
                            Iso3 = "SVN"
                        },
                        new
                        {
                            Id = 202,
                            CountryName = "Solomon Islands",
                            Iso2 = "SB",
                            Iso3 = "SLB"
                        },
                        new
                        {
                            Id = 203,
                            CountryName = "Somalia",
                            Iso2 = "SO",
                            Iso3 = "SOM"
                        },
                        new
                        {
                            Id = 204,
                            CountryName = "South Africa",
                            Iso2 = "ZA",
                            Iso3 = "ZAF"
                        },
                        new
                        {
                            Id = 205,
                            CountryName = "South Georgia",
                            Iso2 = "GS",
                            Iso3 = "SGS"
                        },
                        new
                        {
                            Id = 206,
                            CountryName = "South Sudan",
                            Iso2 = "SS",
                            Iso3 = "SSD"
                        },
                        new
                        {
                            Id = 207,
                            CountryName = "Spain",
                            Iso2 = "ES",
                            Iso3 = "ESP"
                        },
                        new
                        {
                            Id = 208,
                            CountryName = "Sri Lanka",
                            Iso2 = "LK",
                            Iso3 = "LKA"
                        },
                        new
                        {
                            Id = 209,
                            CountryName = "Sudan",
                            Iso2 = "SD",
                            Iso3 = "SDN"
                        },
                        new
                        {
                            Id = 210,
                            CountryName = "Suriname",
                            Iso2 = "SR",
                            Iso3 = "SUR"
                        },
                        new
                        {
                            Id = 211,
                            CountryName = "Svalbard And Jan Mayen Islands",
                            Iso2 = "SJ",
                            Iso3 = "SJM"
                        },
                        new
                        {
                            Id = 212,
                            CountryName = "Eswatini",
                            Iso2 = "SZ",
                            Iso3 = "SWZ"
                        },
                        new
                        {
                            Id = 213,
                            CountryName = "Sweden",
                            Iso2 = "SE",
                            Iso3 = "SWE"
                        },
                        new
                        {
                            Id = 214,
                            CountryName = "Switzerland",
                            Iso2 = "CH",
                            Iso3 = "CHE"
                        },
                        new
                        {
                            Id = 215,
                            CountryName = "Syria",
                            Iso2 = "SY",
                            Iso3 = "SYR"
                        },
                        new
                        {
                            Id = 216,
                            CountryName = "Taiwan",
                            Iso2 = "TW",
                            Iso3 = "TWN"
                        },
                        new
                        {
                            Id = 217,
                            CountryName = "Tajikistan",
                            Iso2 = "TJ",
                            Iso3 = "TJK"
                        },
                        new
                        {
                            Id = 218,
                            CountryName = "Tanzania",
                            Iso2 = "TZ",
                            Iso3 = "TZA"
                        },
                        new
                        {
                            Id = 219,
                            CountryName = "Thailand",
                            Iso2 = "TH",
                            Iso3 = "THA"
                        },
                        new
                        {
                            Id = 220,
                            CountryName = "Togo",
                            Iso2 = "TG",
                            Iso3 = "TGO"
                        },
                        new
                        {
                            Id = 221,
                            CountryName = "Tokelau",
                            Iso2 = "TK",
                            Iso3 = "TKL"
                        },
                        new
                        {
                            Id = 222,
                            CountryName = "Tonga",
                            Iso2 = "TO",
                            Iso3 = "TON"
                        },
                        new
                        {
                            Id = 223,
                            CountryName = "Trinidad And Tobago",
                            Iso2 = "TT",
                            Iso3 = "TTO"
                        },
                        new
                        {
                            Id = 224,
                            CountryName = "Tunisia",
                            Iso2 = "TN",
                            Iso3 = "TUN"
                        },
                        new
                        {
                            Id = 225,
                            CountryName = "Turkey",
                            Iso2 = "TR",
                            Iso3 = "TUR"
                        },
                        new
                        {
                            Id = 226,
                            CountryName = "Turkmenistan",
                            Iso2 = "TM",
                            Iso3 = "TKM"
                        },
                        new
                        {
                            Id = 227,
                            CountryName = "Turks And Caicos Islands",
                            Iso2 = "TC",
                            Iso3 = "TCA"
                        },
                        new
                        {
                            Id = 228,
                            CountryName = "Tuvalu",
                            Iso2 = "TV",
                            Iso3 = "TUV"
                        },
                        new
                        {
                            Id = 229,
                            CountryName = "Uganda",
                            Iso2 = "UG",
                            Iso3 = "UGA"
                        },
                        new
                        {
                            Id = 230,
                            CountryName = "Ukraine",
                            Iso2 = "UA",
                            Iso3 = "UKR"
                        },
                        new
                        {
                            Id = 231,
                            CountryName = "United Arab Emirates",
                            Iso2 = "AE",
                            Iso3 = "ARE"
                        },
                        new
                        {
                            Id = 232,
                            CountryName = "United Kingdom",
                            Iso2 = "GB",
                            Iso3 = "GBR"
                        },
                        new
                        {
                            Id = 233,
                            CountryName = "United States of America",
                            Iso2 = "US",
                            Iso3 = "USA"
                        },
                        new
                        {
                            Id = 234,
                            CountryName = "United States Minor Outlying Islands",
                            Iso2 = "UM",
                            Iso3 = "UMI"
                        },
                        new
                        {
                            Id = 235,
                            CountryName = "Uruguay",
                            Iso2 = "UY",
                            Iso3 = "URY"
                        },
                        new
                        {
                            Id = 236,
                            CountryName = "Uzbekistan",
                            Iso2 = "UZ",
                            Iso3 = "UZB"
                        },
                        new
                        {
                            Id = 237,
                            CountryName = "Vanuatu",
                            Iso2 = "VU",
                            Iso3 = "VUT"
                        },
                        new
                        {
                            Id = 238,
                            CountryName = "Vatican City State (Holy See)",
                            Iso2 = "VA",
                            Iso3 = "VAT"
                        },
                        new
                        {
                            Id = 239,
                            CountryName = "Venezuela",
                            Iso2 = "VE",
                            Iso3 = "VEN"
                        },
                        new
                        {
                            Id = 240,
                            CountryName = "Vietnam",
                            Iso2 = "VN",
                            Iso3 = "VNM"
                        },
                        new
                        {
                            Id = 241,
                            CountryName = "Virgin Islands (British)",
                            Iso2 = "VG",
                            Iso3 = "VGB"
                        },
                        new
                        {
                            Id = 242,
                            CountryName = "Virgin Islands (US)",
                            Iso2 = "VI",
                            Iso3 = "VIR"
                        },
                        new
                        {
                            Id = 243,
                            CountryName = "Wallis And Futuna Islands",
                            Iso2 = "WF",
                            Iso3 = "WLF"
                        },
                        new
                        {
                            Id = 244,
                            CountryName = "Western Sahara",
                            Iso2 = "EH",
                            Iso3 = "ESH"
                        },
                        new
                        {
                            Id = 245,
                            CountryName = "Yemen",
                            Iso2 = "YE",
                            Iso3 = "YEM"
                        },
                        new
                        {
                            Id = 246,
                            CountryName = "Zambia",
                            Iso2 = "ZM",
                            Iso3 = "ZMB"
                        },
                        new
                        {
                            Id = 247,
                            CountryName = "Zimbabwe",
                            Iso2 = "ZW",
                            Iso3 = "ZWE"
                        },
                        new
                        {
                            Id = 248,
                            CountryName = "Kosovo",
                            Iso2 = "XK",
                            Iso3 = "XKX"
                        },
                        new
                        {
                            Id = 249,
                            CountryName = "Curaçao",
                            Iso2 = "CW",
                            Iso3 = "CUW"
                        },
                        new
                        {
                            Id = 250,
                            CountryName = "Sint Maarten (Dutch part)",
                            Iso2 = "SX",
                            Iso3 = "SXM"
                        },
                        new
                        {
                            Id = 251,
                            CountryName = "Cyprus, Turkish Republic of Northern",
                            Iso2 = "CY",
                            Iso3 = "CYP"
                        },
                        new
                        {
                            Id = 252,
                            CountryName = "South Georgia and the South Sandwich Islands",
                            Iso2 = "GS",
                            Iso3 = "SGS"
                        });
                });

            modelBuilder.Entity("eSim.EF.Entities.GlobalSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("FixedCommission")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PercentageCommission")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Settings", "master");
                });

            modelBuilder.Entity("eSim.EF.Entities.OTPVerification", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit");

                    b.Property<string>("OTP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OTPVerification");
                });

            modelBuilder.Entity("eSim.EF.Entities.SideMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ControllerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SideMenu");
                });

            modelBuilder.Entity("eSim.EF.Entities.Subscribers", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsEmailVerifired")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProfileImage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("TermsAndConditions")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Subscribers", "client");
                });

            modelBuilder.Entity("eSim.EF.Entities.SystemClaims", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SystemClaims");
                });

            modelBuilder.Entity("eSim.EF.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("TRN")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("TicketType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Ticket", "client");
                });

            modelBuilder.Entity("eSim.EF.Entities.TicketActivities", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ActivityAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ActivityBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("CommentType")
                        .HasColumnType("int");

                    b.Property<bool>("IsVisibleToCustomer")
                        .HasColumnType("bit");

                    b.Property<string>("TicketId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TicketActivities", "client");
                });

            modelBuilder.Entity("eSim.EF.Entities.TicketAttachmentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttachmentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TicketAttachmentType", "ref");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AttachmentType = "Internal"
                        },
                        new
                        {
                            Id = 2,
                            AttachmentType = "External"
                        });
                });

            modelBuilder.Entity("eSim.EF.Entities.TicketAttachments", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ActivityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Attachment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AttachmentType")
                        .HasColumnType("int");

                    b.Property<string>("TicketId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TicketAttachments", "client");
                });

            modelBuilder.Entity("eSim.EF.Entities.TicketCommentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CommentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TicketCommentType", "ref");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CommentType = "Customer"
                        },
                        new
                        {
                            Id = 2,
                            CommentType = "Admin"
                        });
                });

            modelBuilder.Entity("eSim.EF.Entities.TicketStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TicketStatus", "ref");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Status = "Open"
                        },
                        new
                        {
                            Id = 2,
                            Status = "Close"
                        },
                        new
                        {
                            Id = 3,
                            Status = "In-progress"
                        },
                        new
                        {
                            Id = 4,
                            Status = "Waiting for reply"
                        });
                });

            modelBuilder.Entity("eSim.EF.Entities.TicketType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TicketType", "ref");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Type = "Bundle"
                        },
                        new
                        {
                            Id = 2,
                            Type = "Payment"
                        });
                });

            modelBuilder.Entity("eSim.EF.Entities.ApplicationRole", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityRole");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("ApplicationRole");
                });

            modelBuilder.Entity("eSim.EF.Entities.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("ParentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserRoleId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("ApplicationUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("eSim.EF.Entities.ClientSettings", b =>
                {
                    b.HasOne("eSim.EF.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });
#pragma warning restore 612, 618
        }
    }
}
