using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace eSim.EF.Migrations
{
    /// <inheritdoc />
    public partial class AlterCountriesData : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Countries",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    CountryName = table.Column<string>(type: "nvarchar(255)", maxLength: 255, nullable: false),
                    Iso3 = table.Column<string>(type: "nvarchar(3)", maxLength: 3, nullable: false),
                    Iso2 = table.Column<string>(type: "nvarchar(2)", maxLength: 2, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Countries", x => x.Id);
                });

            migrationBuilder.InsertData(
                table: "Countries",
                columns: new[] { "Id", "CountryName", "Iso2", "Iso3" },
                values: new object[,]
                {
                    { 1, "Afghanistan", "AF", "AFG" },
                    { 2, "Aland Islands", "AX", "ALA" },
                    { 3, "Albania", "AL", "ALB" },
                    { 4, "Algeria", "DZ", "DZA" },
                    { 5, "American Samoa", "AS", "ASM" },
                    { 6, "Andorra", "AD", "AND" },
                    { 7, "Angola", "AO", "AGO" },
                    { 8, "Anguilla", "AI", "AIA" },
                    { 9, "Antarctica", "AQ", "ATA" },
                    { 10, "Antigua And Barbuda", "AG", "ATG" },
                    { 11, "Argentina", "AR", "ARG" },
                    { 12, "Armenia", "AM", "ARM" },
                    { 13, "Aruba", "AW", "ABW" },
                    { 14, "Australia", "AU", "AUS" },
                    { 15, "Austria", "AT", "AUT" },
                    { 16, "Azerbaijan", "AZ", "AZE" },
                    { 17, "Bahamas The", "BS", "BHS" },
                    { 18, "Bahrain", "BH", "BHR" },
                    { 19, "Bangladesh", "BD", "BGD" },
                    { 20, "Barbados", "BB", "BRB" },
                    { 21, "Belarus", "BY", "BLR" },
                    { 22, "Belgium", "BE", "BEL" },
                    { 23, "Belize", "BZ", "BLZ" },
                    { 24, "Benin", "BJ", "BEN" },
                    { 25, "Bermuda", "BM", "BMU" },
                    { 26, "Bhutan", "BT", "BTN" },
                    { 27, "Bolivia", "BO", "BOL" },
                    { 28, "Bosnia and Herzegovina", "BA", "BIH" },
                    { 29, "Botswana", "BW", "BWA" },
                    { 30, "Bouvet Island", "BV", "BVT" },
                    { 31, "Brazil", "BR", "BRA" },
                    { 32, "British Indian Ocean Territory", "IO", "IOT" },
                    { 33, "Brunei", "BN", "BRN" },
                    { 34, "Bulgaria", "BG", "BGR" },
                    { 35, "Burkina Faso", "BF", "BFA" },
                    { 36, "Burundi", "BI", "BDI" },
                    { 37, "Cambodia", "KH", "KHM" },
                    { 38, "Cameroon", "CM", "CMR" },
                    { 39, "Canada", "CA", "CAN" },
                    { 40, "Cape Verde", "CV", "CPV" },
                    { 41, "Cayman Islands", "KY", "CYM" },
                    { 42, "Central African Republic", "CF", "CAF" },
                    { 43, "Chad", "TD", "TCD" },
                    { 44, "Chile", "CL", "CHL" },
                    { 45, "China", "CN", "CHN" },
                    { 46, "Christmas Island", "CX", "CXR" },
                    { 47, "Cocos (Keeling) Islands", "CC", "CCK" },
                    { 48, "Colombia", "CO", "COL" },
                    { 49, "Comoros", "KM", "COM" },
                    { 50, "Congo, The Republic of", "CG", "COG" },
                    { 51, "Congo The Democratic Republic Of The", "CD", "COD" },
                    { 52, "Cook Islands", "CK", "COK" },
                    { 53, "Costa Rica", "CR", "CRI" },
                    { 54, "Cote D'Ivoire (Ivory Coast)", "CI", "CIV" },
                    { 55, "Croatia (Hrvatska)", "HR", "HRV" },
                    { 56, "Cuba", "CU", "CUB" },
                    { 57, "Cyprus, Republic of", "CY", "CYP" },
                    { 58, "Czech Republic", "CZ", "CZE" },
                    { 59, "Denmark", "DK", "DNK" },
                    { 60, "Djibouti", "DJ", "DJI" },
                    { 61, "Dominica", "DM", "DMA" },
                    { 62, "Dominican Republic", "DO", "DOM" },
                    { 63, "East Timor", "TL", "TLS" },
                    { 64, "Ecuador", "EC", "ECU" },
                    { 65, "Egypt", "EG", "EGY" },
                    { 66, "El Salvador", "SV", "SLV" },
                    { 67, "Equatorial Guinea", "GQ", "GNQ" },
                    { 68, "Eritrea", "ER", "ERI" },
                    { 69, "Estonia", "EE", "EST" },
                    { 70, "Ethiopia", "ET", "ETH" },
                    { 71, "Falkland Islands", "FK", "FLK" },
                    { 72, "Faroe Islands", "FO", "FRO" },
                    { 73, "Fiji Islands", "FJ", "FJI" },
                    { 74, "Finland", "FI", "FIN" },
                    { 75, "France", "FR", "FRA" },
                    { 76, "French Guiana", "GF", "GUF" },
                    { 77, "French Polynesia", "PF", "PYF" },
                    { 78, "French Southern Territories", "TF", "ATF" },
                    { 79, "Gabon", "GA", "GAB" },
                    { 80, "Gambia The", "GM", "GMB" },
                    { 81, "Georgia", "GE", "GEO" },
                    { 82, "Germany", "DE", "DEU" },
                    { 83, "Ghana", "GH", "GHA" },
                    { 84, "Gibraltar", "GI", "GIB" },
                    { 85, "Greece", "GR", "GRC" },
                    { 86, "Greenland", "GL", "GRL" },
                    { 87, "Grenada", "GD", "GRD" },
                    { 88, "Guadeloupe", "GP", "GLP" },
                    { 89, "Guam", "GU", "GUM" },
                    { 90, "Guatemala", "GT", "GTM" },
                    { 91, "Guernsey and Alderney", "GG", "GGY" },
                    { 92, "Guinea", "GN", "GIN" },
                    { 93, "Guinea-Bissau", "GW", "GNB" },
                    { 94, "Guyana", "GY", "GUY" },
                    { 95, "Haiti", "HT", "HTI" },
                    { 96, "Heard Island and McDonald Islands", "HM", "HMD" },
                    { 97, "Honduras", "HN", "HND" },
                    { 98, "Hong Kong S.A.R.", "HK", "HKG" },
                    { 99, "Hungary", "HU", "HUN" },
                    { 100, "Iceland", "IS", "ISL" },
                    { 101, "India", "IN", "IND" },
                    { 102, "Indonesia", "ID", "IDN" },
                    { 103, "Iran", "IR", "IRN" },
                    { 104, "Iraq", "IQ", "IRQ" },
                    { 105, "Ireland", "IE", "IRL" },
                    { 106, "Israel", "IL", "ISR" },
                    { 107, "Italy", "IT", "ITA" },
                    { 108, "Jamaica", "JM", "JAM" },
                    { 109, "Japan", "JP", "JPN" },
                    { 110, "Jersey", "JE", "JEY" },
                    { 111, "Jordan", "JO", "JOR" },
                    { 112, "Kazakhstan", "KZ", "KAZ" },
                    { 113, "Kenya", "KE", "KEN" },
                    { 114, "Kiribati", "KI", "KIR" },
                    { 115, "South Korea (Republic of)", "KP", "PRK" },
                    { 116, "North Korea (Democratic People's Republic of)", "KR", "KOR" },
                    { 117, "Kuwait", "KW", "KWT" },
                    { 118, "Kyrgyzstan", "KG", "KGZ" },
                    { 119, "Laos", "LA", "LAO" },
                    { 120, "Latvia", "LV", "LVA" },
                    { 121, "Lebanon", "LB", "LBN" },
                    { 122, "Lesotho", "LS", "LSO" },
                    { 123, "Liberia", "LR", "LBR" },
                    { 124, "Libya", "LY", "LBY" },
                    { 125, "Liechtenstein", "LI", "LIE" },
                    { 126, "Lithuania", "LT", "LTU" },
                    { 127, "Luxembourg", "LU", "LUX" },
                    { 128, "Macau S.A.R.", "MO", "MAC" },
                    { 129, "North Macedonia", "MK", "MKD" },
                    { 130, "Madagascar", "MG", "MDG" },
                    { 131, "Malawi", "MW", "MWI" },
                    { 132, "Malaysia", "MY", "MYS" },
                    { 133, "Maldives", "MV", "MDV" },
                    { 134, "Mali", "ML", "MLI" },
                    { 135, "Malta", "MT", "MLT" },
                    { 136, "Man (Isle of)", "IM", "IMN" },
                    { 137, "Marshall Islands", "MH", "MHL" },
                    { 138, "Martinique", "MQ", "MTQ" },
                    { 139, "Mauritania", "MR", "MRT" },
                    { 140, "Mauritius", "MU", "MUS" },
                    { 141, "Mayotte", "YT", "MYT" },
                    { 142, "Mexico", "MX", "MEX" },
                    { 143, "Micronesia", "FM", "FSM" },
                    { 144, "Moldova", "MD", "MDA" },
                    { 145, "Monaco", "MC", "MCO" },
                    { 146, "Mongolia", "MN", "MNG" },
                    { 147, "Montenegro", "ME", "MNE" },
                    { 148, "Montserrat", "MS", "MSR" },
                    { 149, "Morocco", "MA", "MAR" },
                    { 150, "Mozambique", "MZ", "MOZ" },
                    { 151, "Myanmar", "MM", "MMR" },
                    { 152, "Namibia", "NA", "NAM" },
                    { 153, "Nauru", "NR", "NRU" },
                    { 154, "Nepal", "NP", "NPL" },
                    { 155, "Bonaire, Sint Eustatius and Saba", "BQ", "BES" },
                    { 156, "Netherlands The", "NL", "NLD" },
                    { 157, "New Caledonia", "NC", "NCL" },
                    { 158, "New Zealand", "NZ", "NZL" },
                    { 159, "Nicaragua", "NI", "NIC" },
                    { 160, "Niger", "NE", "NER" },
                    { 161, "Nigeria", "NG", "NGA" },
                    { 162, "Niue", "NU", "NIU" },
                    { 163, "Norfolk Island", "NF", "NFK" },
                    { 164, "Northern Mariana Islands", "MP", "MNP" },
                    { 165, "Norway", "NO", "NOR" },
                    { 166, "Oman", "OM", "OMN" },
                    { 167, "Pakistan", "PK", "PAK" },
                    { 168, "Palau", "PW", "PLW" },
                    { 169, "Palestine", "PS", "PSE" },
                    { 170, "Panama", "PA", "PAN" },
                    { 171, "Papua New Guinea", "PG", "PNG" },
                    { 172, "Paraguay", "PY", "PRY" },
                    { 173, "Peru", "PE", "PER" },
                    { 174, "Philippines", "PH", "PHL" },
                    { 175, "Pitcairn Island", "PN", "PCN" },
                    { 176, "Poland", "PL", "POL" },
                    { 177, "Portugal", "PT", "PRT" },
                    { 178, "Puerto Rico", "PR", "PRI" },
                    { 179, "Qatar", "QA", "QAT" },
                    { 180, "Reunion", "RE", "REU" },
                    { 181, "Romania", "RO", "ROU" },
                    { 182, "Russia", "RU", "RUS" },
                    { 183, "Rwanda", "RW", "RWA" },
                    { 184, "Saint Helena", "SH", "SHN" },
                    { 185, "Saint Kitts And Nevis", "KN", "KNA" },
                    { 186, "Saint Lucia", "LC", "LCA" },
                    { 187, "Saint Pierre and Miquelon", "PM", "SPM" },
                    { 188, "Saint Vincent And The Grenadines", "VC", "VCT" },
                    { 189, "Saint-Barthelemy", "BL", "BLM" },
                    { 190, "Saint-Martin (French part)", "MF", "MAF" },
                    { 191, "Samoa", "WS", "WSM" },
                    { 192, "San Marino", "SM", "SMR" },
                    { 193, "Sao Tome and Principe", "ST", "STP" },
                    { 194, "Saudi Arabia", "SA", "SAU" },
                    { 195, "Senegal", "SN", "SEN" },
                    { 196, "Serbia", "RS", "SRB" },
                    { 197, "Seychelles", "SC", "SYC" },
                    { 198, "Sierra Leone", "SL", "SLE" },
                    { 199, "Singapore", "SG", "SGP" },
                    { 200, "Slovakia", "SK", "SVK" },
                    { 201, "Slovenia", "SI", "SVN" },
                    { 202, "Solomon Islands", "SB", "SLB" },
                    { 203, "Somalia", "SO", "SOM" },
                    { 204, "South Africa", "ZA", "ZAF" },
                    { 205, "South Georgia", "GS", "SGS" },
                    { 206, "South Sudan", "SS", "SSD" },
                    { 207, "Spain", "ES", "ESP" },
                    { 208, "Sri Lanka", "LK", "LKA" },
                    { 209, "Sudan", "SD", "SDN" },
                    { 210, "Suriname", "SR", "SUR" },
                    { 211, "Svalbard And Jan Mayen Islands", "SJ", "SJM" },
                    { 212, "Eswatini", "SZ", "SWZ" },
                    { 213, "Sweden", "SE", "SWE" },
                    { 214, "Switzerland", "CH", "CHE" },
                    { 215, "Syria", "SY", "SYR" },
                    { 216, "Taiwan", "TW", "TWN" },
                    { 217, "Tajikistan", "TJ", "TJK" },
                    { 218, "Tanzania", "TZ", "TZA" },
                    { 219, "Thailand", "TH", "THA" },
                    { 220, "Togo", "TG", "TGO" },
                    { 221, "Tokelau", "TK", "TKL" },
                    { 222, "Tonga", "TO", "TON" },
                    { 223, "Trinidad And Tobago", "TT", "TTO" },
                    { 224, "Tunisia", "TN", "TUN" },
                    { 225, "Turkey", "TR", "TUR" },
                    { 226, "Turkmenistan", "TM", "TKM" },
                    { 227, "Turks And Caicos Islands", "TC", "TCA" },
                    { 228, "Tuvalu", "TV", "TUV" },
                    { 229, "Uganda", "UG", "UGA" },
                    { 230, "Ukraine", "UA", "UKR" },
                    { 231, "United Arab Emirates", "AE", "ARE" },
                    { 232, "United Kingdom", "GB", "GBR" },
                    { 233, "United States of America", "US", "USA" },
                    { 234, "United States Minor Outlying Islands", "UM", "UMI" },
                    { 235, "Uruguay", "UY", "URY" },
                    { 236, "Uzbekistan", "UZ", "UZB" },
                    { 237, "Vanuatu", "VU", "VUT" },
                    { 238, "Vatican City State (Holy See)", "VA", "VAT" },
                    { 239, "Venezuela", "VE", "VEN" },
                    { 240, "Vietnam", "VN", "VNM" },
                    { 241, "Virgin Islands (British)", "VG", "VGB" },
                    { 242, "Virgin Islands (US)", "VI", "VIR" },
                    { 243, "Wallis And Futuna Islands", "WF", "WLF" },
                    { 244, "Western Sahara", "EH", "ESH" },
                    { 245, "Yemen", "YE", "YEM" },
                    { 246, "Zambia", "ZM", "ZMB" },
                    { 247, "Zimbabwe", "ZW", "ZWE" },
                    { 248, "Kosovo", "XK", "XKX" },
                    { 249, "Curaçao", "CW", "CUW" },
                    { 250, "Sint Maarten (Dutch part)", "SX", "SXM" },
                    { 251, "Cyprus, Turkish Republic of Northern", "CY", "CYP" },
                    { 252, "South Georgia and the South Sandwich Islands", "GS", "SGS" }
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Countries");
        }
    }
}
